udo: false

language: java
jdk: oraclejdk8

cache:
  directories:
    - '$HOME/.m2/repository'

script:
  - mvn dependency:purge-local-repository -DactTransitively=false -DreResolve=false
  - mvn clean install