# Get your APIKey from the MinecraftMarket panel
APIKey: randomstring
# Time between purchases and donors checks in minutes
CheckInterval: 1
# Ingame GUI shop commands
ShopCommands:
- "Shop"
- "Buy"
# Enable ingame GUI used by ShopCommands
UseGUI: true
# Enable recent donors signs
UseSigns: true
# Date format to use on recent donors signs
DateFormat: yyyy-MM-dd
# Default skin to use on heads when account is cracked or request fails
DefaultHeadSkin: https://textures.minecraft.net/texture/5163dafac1d91a8c91db576caac784336791a6e18d8f7f62778fc47bf146b6
# Language to use on messages language files located at langs folder
Lang: en
# Log errors no need to activate this
Debug: false