name: ${project.name}
version: ${project.version}
main: com.minecraftmarket.minecraftmarket.bukkit.MCMarket
softdepend: [Multiverse-Core, MultiWorld]
authors: [R4G3_BABY, NLThijs48]
description: ${project.description}
website: ${project.url}

commands:
  MinecraftMarket:
    permission: minecraftmarket.use
    description: Manage plugin functionalities
    aliases: [mm]
    usage: /<command> <args>

permissions:
  minecraftmarket.use:
    description: Allows main command usage
    default: op
  minecraftmarket.signs:
    description: Can break signs to remove them
    default: op