# Get your APIKey from the MinecraftMarket panel
APIKey: randomstring
# Time between purchases and donors checks in minutes
CheckInterval: 1
# Enable recent donors signs
UseSigns: true
# Date format to use on recent donors signs
DateFormat: yyyy-MM-dd
# Language to use on messages language files located at langs folder
Lang: en
# Log errors no need to activate this
Debug: false